### ISSUE TITLE
Gracefully handle failed "get block by number" JRPC calls

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/block-oracle#121]
The hot-fix in e9b64bf7660ae6093bc4a795286b9d9e214af71d addressed an unlikely error, for when a provider is unable to provide a block whose number it has just given us.

We should create a new error path for that situation and handle it accordingly.

Most likely, we should consider that block request as a failed attempt, but this is up to discussion.

**Comment by neysofu** [comment]
Fixed with https://github.com/graphprotocol/block-oracle/pull/138. Now we only send one JRPC request to get the latest block number, including its hash and other related info, so we don't have any data consistency problems anymore across two calls. The call itself can still fail, but it's orthogonal to this issue. Closing.
